/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-2",
  aws_cognito_identity_pool_id:
    "ap-northeast-2:748bd95b-d164-49d2-847c-71bad6186152",
  aws_cognito_region: "ap-northeast-2",
  aws_user_pools_id: "ap-northeast-2_8SJ1QxkQS",
  aws_user_pools_web_client_id: "6u0heihef1p2aa0lkehl1klr2j",
  oauth: {},
};

export default awsmobile;
